version: '3.3'
services:


  # db:
  #   container_name: db
  #   image: postgres:13.0-alpine
  #   volumes:
  #     - /var/lib/postgresql/data/
  #   env_file:
  #     - ./.env

  # backend:
  #   container_name: backend
  #   build: ../backend/
  #   # image: mlisnevsky/mistigo:latest
  #   restart: always
  #   volumes:
  #     - static_value:/app/static_backend/
  #     - media_value:/app/media/ 
  #   depends_on:
  #     - db
  #   env_file:
  #     - ./.env

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
      # -  static_value:/app/result_build/static/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
#       - static_value:/usr/share/nginx/html/static_backend/
#       - media_value:/usr/share/nginx/html/media/


# volumes:
#   static_value:
#   media_value: