# Generated by Django 3.2.15 on 2023-01-30 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Пользователи'},
        ),
    ]
